jobs:
  - title: "Head of Education & IT"
    organization: "42 Angoulême"
    start_date: "Aug. 2021"
    end_date: "Feb. 2026"
    location: "France"
    focus: "Tech, Product, Relations, Pedagogy & Operations"
    overview: "Spearheaded the campus launch from day one, scaling to 592 students and fostering 30+ corporate partnerships."
    achievements:
      - description: "Projects & Product Management"
        sub:
          - description: "End-to-end Product Ownership of an educational platform used by the entire student body, applicants, and staff:"
            sub:
              - description: "Designed and architected the application, contributed to its development, drove technical decision-making & reviews from conception to delivery, resulting in a 70k LoC web, mobile & desktop Full Stack Rust codebase (Axum / Dioxus / Tailwind) leveraging DDD and MVC architectures."
              - description: "Directed product strategy and team execution: designed the roadmap and features, managed the backlog, and led the team."
              - description: "Key Features: Dynamic form builder, Ticketing & feedback system, Resource sharing hub, Applicant selection tool, Advanced curriculum projection, Academic records, Administrative automation, Scheduler, Notification center."
          - description: "Designed a Rust open-source, cross-platform UI Component Library (Dioxus)"
            link: "https://github.com/42Angouleme/dioxus-tw-components"
          - description: "Steered an open source, documented embedded AI library (Python / R.Pi) designed for hands-on STEM education. Led on-site programming & AI workshops."
            link: "https://github.com/42Angouleme/pybot"
      - description: "Corporate Relations"
        sub:
          - description: "Acted as the primary bridge between the campus, the regional tech ecosystem (spanning startups to large enterprises) and public actors."
          - description: "Fostered trust-based relationships through direct exchanges with C-level and operational staff, translating business expectations into recruitment and partnerships."
          - description: "Delivered technical and educational presentations to diverse audiences of up to 150 attendees (primarily in french)."
      - description: "Campus Operations"
        sub:
          - description: "Recruited, mentored, and managed a cross-functional IT and pedagogy team of 4 juniors."
          - description: "Individually assessed and selected the entire student body from thousands of applicants based on an intensive 26-day on-site technical immersion."
          - description: "Provided ongoing pedagogical, professional, and entrepreneurial mentoring to students, both individually and collectively."

  - title: "Software Engineer"
    organization: "SAS Normation (Rudder)"
    start_date: "Dec. 2019"
    end_date: "March 2021"
    location: "Paris, France"
    focus: "Core developer of rudder-lang"
    overview: "A declarative Infrastructure-as-Code language written in Rust."
    achievements:
      - description: "Contributed to the development of the open source compiler toolchain (lexer, parser, AST, semantic analysis, transpiler)."
        link: "https://github.com/Normation/rudder/tree/branches/rudder/6.2/rudder-lang"
      - description: "Wrote comprehensive unit and integration tests following DDD principles."
      - description: "Authored technical and user documentation; published a technical article."
        link: "https://www.rudder.io/blog/rudder-lang-introduction/"
      - description: "Managed and prioritized the technical backlog."

  - title: "Full Stack Web Developer"
    organization: "uRehab"
    start_date: "Sep. 2017"
    end_date: "Jan. 2018"
    location: "Paris, France"
    focus: "Software Engineer Intern (chatbots)"
    achievements:
      - description: "Designed and built Frontend interfaces (React)."
      - description: "Wrote API and conversational logic (NodeJS) and modeled data (MongoDB)."

education:
  - title: "42 Paris - Digital Technologies Architect"
    organization: "42"
    start_date: "2016"
    end_date: "2020"
    location: "Paris, France"
    focus: "Project-based curriculum emphasizing peer collaboration and autonomy"
    overview: "(MSc Eq.)"
    achievements:
      - description: "System & Web Engineering (Unix/C/C++/Rust, Algorithms, Rendering, Security, JS)."
      - description: "Awarded at Hackathons: 42Startup, SexTechLab, Société Générale."

  - title: "Law Bachelor Degree in Private Law"
    organization: "Burgundy University"
    start_date: "2012"
    end_date: "2016"
    location: "Dijon, France"
    focus: "These years shaped my work capacity, academic rigor, and logical reasoning"
