[[projects]]
description = "Développement de librairies Rust (web & logiciel)."
description = "Déploiement automatisé d’une infrastructure (Ansible), avec services et pipeline CI/CD."
description = "Conception et développement d’un jeu multijoueur sur Unreal Engine (2020-2022)."
description = "Co-création d’un bot conversationnel de prévention santé pour adolescents (2017)."
description = "Écriture : livres blancs, fiction, blog de connaissances."
