[[projects]]
description = "Development of Rust libraries (web & software)."
description = "Setup of self-hosted infrastructure and CI/CD pipelines."
description = "Writing: white papers, fiction, and a knowledge-sharing blog."
description = "Game development of a multiplayer video game using Unreal Engine (2020-2021)."
description = "Created a conversational bot for adolescent health prevention (2017)."
